version: "3.8"

services:
  db:
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "atendimento", "-d", "atendimento"]
      interval: 5s
      timeout: 3s
      retries: 5
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: atendimento
      POSTGRES_PASSWORD: ZdG387FhYsm0olSm097541HMSdS=
      POSTGRES_DB: atendimento
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: .
    container_name: backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: atendimento
      DB_PASS: ZdG387FhYsm0olSm097541HMSdS=
      DB_NAME: atendimento
      JWT_SECRET: 3123123213123
      JWT_REFRESH_SECRET: 75756756756
      REDIS_URI: redis://redis:6379
      REDIS_PORT: 6379
      FFMPEG_PATH: "/usr/bin/ffmpeg"
    ports:
      - "8089:8089"
    volumes:
      - .:/app

volumes:
  pg_data:
  redis_data:
